### ISSUE TITLE
Publish public version of Phase 2 board slides

### ISSUE THREAD

**Issue by bhuvanshri** [MozillaFoundation/strategy#45]
- [ ] Review slide deck and make edits if required
  - [ ] Add watermark on each slide
  - [ ] Update the cover slide
- [ ] Publish deck as: 
  - [ ] Google Slides - To be embedded on Wiki
  - [ ] PDF - linked on wiki
  - [ ] YouTube video - published on Mark's blog - For you @OpenMatt 
  - [ ] Create MoFo slideshare account and publish there (+ pass credentials to @OpenMatt and Kevin)
  - [ ] Publish slides as individual images - Google Drive folder to be shared publicly (Need watermark on each slide for this)
- [ ] Publish "Staging" wiki

**Comment by bhuvanshri** [comment]
@OpenMatt No, we haven't updated the wiki yet with the October Board meeting updates yet.

**Comment by OpenMatt** [comment]
ok. At this point we should probably just focus on the Dec one.
