### ISSUE TITLE
Create Google Slide template

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/strategy#48]
* Goal: turn the slide template we used in the October board meeting (color palette, type, etc) into a Google Slide template we can use for the December board meeting
* Being able to work in Google Slides (instead of Keynote / Illustrator) will pay off *huge * efficiencies
* If possible to get done this week, Mark will start using it.

**Comment by OpenMatt** [comment]
@cassiemc ok to have @lovegushwa work on this this week?

**Comment by flukeout** [comment]
I got this.

@OpenMatt Can you link me to the Board Meeting one?
@vazquez - Do you have the deck handy that you used for the Webmaker hashtag features? 
@kristinashu - You were working on a Google Presentation deck recently, can I have a link? What was it for?

**Comment by vazquez** [comment]
@flukeout - Here it is man: https://docs.google.com/a/mozilla.com/presentation/d/19TgHgfrDtbm3Q7VLKRcfyxb20pqSPFrcCP9qW2dmJUw/edit?usp=sharing

**Comment by cassiemc** [comment]
@OpenMatt – @lovegushwa is tied up with EOY work this week so @flukeout will help. Thanks a bunch Luke!

**Comment by kristinashu** [comment]
@flukeout here's the deck for MozFest presenter slides https://docs.google.com/a/mozilla.com/presentation/d/1--8UMoYpWzB6O0AG4AosxzKRnn3k4t17QyxrdjC5PYU/edit?usp=sharing
and here's the generic mozilla template https://docs.google.com/a/mozilla.com/presentation/d/1zFIqJk57BhmVCpBEG8CIY0C0BdNeZCK-dC8uhbEvmFQ/edit?usp=sharing

**Comment by lovegushwa** [comment]
@flukeout your rad thank you! 
(1)@OpenMatt specifically wants to build a google slides template of this keynote presentation I built:
https://drive.google.com/a/mozilla.com/file/d/0B2qu3ExKWIlvTlJ4Sndsd1VnaG8/view?usp=sharing

(2) It originally came from this slide deck Mark was building for the last board meeting:
https://drive.google.com/a/mozilla.com/file/d/0B2qu3ExKWIlvcksza3JkMHFrdW8/view?usp=sharing

The big idea here: This template needs to look like the finished presentation (1) but be a template Mark can build on and edit (2) without much final polish (or any) from a graphic designer.

**Comment by OpenMatt** [comment]
thanks guys. just to reiterate what jordan mentioned -- @msurman wants a carbon copy of these. No aesthetic changes needed -- just turning what we did in the last presentation into a Google slides version. 

https://drive.google.com/a/mozilla.com/file/d/0B2qu3ExKWIlvTlJ4Sndsd1VnaG8/view?usp=sharing
https://drive.google.com/a/mozilla.com/file/d/0B2qu3ExKWIlvcksza3JkMHFrdW8/view?usp=sharing

**Comment by flukeout** [comment]
@OpenMatt Okay - so just to clarify, you want an exact slide-by-slide replica of that deck in google presentations? Or are we looking for more of a template presentation that has the same colors and layout options?

**Comment by flukeout** [comment]
@OpenMatt Here's what I've got so far...

https://docs.google.com/a/mozilla.com/presentation/d/1iNKTFP-h6TJAWbHuAb5T1zkiIcZnxrdeYqcI9GwxuOc/edit?usp=sharing

It's an assortment of the various layouts and images used in the Board Presentation along with some master slide templates that have the common styles in each of the 3 background colors. When you have a chance, please give me a ping so I figure out how to proceed.

**Comment by OpenMatt** [comment]
@flukeout awesome! I'll have a look Wed morning. @natalieworth + @cassiemc looks like @flukeout may already be done -- will update here.

**Comment by OpenMatt** [comment]
@flukeout r+ looks awesome. Thank you for doing this so fast and so well.

**Comment by OpenMatt** [comment]
http://mzl.la/slide_template
