### ISSUE TITLE
Design help for Dec board presentation

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/strategy#49]
- Mark has started working on content for the Dec 16 board presentation
- At some point he'll need some lightweight design help. Should be a much lighter lift than the last board meeting. But want to flag @cassiemc and @lovegushwa early.

**Comment by cassiemc** [comment]
@OpenMatt Is something due for the Nov 27 milestone or was that just to get people's attention?

**Comment by OpenMatt** [comment]
@cassiemc Just hoping that a designer and Mark can have a kick-off meeting this week.

**Comment by cassiemc** [comment]
@OpenMatt – @natalieworth is on board to help out with this, she just has a couple EOY tasks to finish up over the next couple days. Hopefully @lovegushwa can attend the kickoff too in order to art direct, but otherwise he'll be on PTO next week.

**Comment by OpenMatt** [comment]
@cassiemc I just got a request from Mark to get some design help for a presentation he's giving Mon, Nov 30. Ideally it would use this same template. Possible to get some design help for that on Thurs or Fri? Or too tight?

**Comment by cassiemc** [comment]
That sounds doable to me @OpenMatt, given what I know of @natalieworth's current workload. She can use the template @flukeout is making in #48, right? 
Natalie, does this sound good?

**Comment by OpenMatt** [comment]
correct! thanks!

**Comment by natalieworth** [comment]
Yah! Sounds good @cassiemc @OpenMatt

**Comment by natalieworth** [comment]
Hey @OpenMatt, I'm free Thurs and Fri after 11am anytime to meet and help out with this for the Nov. 30 presentation and the board presentation. Feel free to email/ send content to me (or set up a meeting if easier) at natalie@mozillafoundation.org as Jordan's on PTO for the rest of the week and next. Thanks!

**Comment by OpenMatt** [comment]
Thanks @natalieworth . Let's push ahead in this ticket: https://github.com/MozillaFoundation/strategy/issues/62

**Comment by OpenMatt** [comment]
- @cassiemc Want to flag that once we get back from Orlando, @msurman will need a designer on deck to help w. design work on the board slides. We should ensure a designer is available for work on this Dec 14, 15 and 16. There may not be a full 3 days of work required, but we should have one available on deck as needed. Does that work? 
- Note also: I will be away that week. So the designer will be working directly with Mark / Angela / Ops.

**Comment by cassiemc** [comment]
@natalieworth should still be on board to help with this. I'll check in with @lovegushwa this week as well to find out his schedule next week too.

**Comment by OpenMatt** [comment]
great thanks!

**Comment by natalieworth** [comment]
I can help with these next week @OpenMatt

**Comment by OpenMatt** [comment]
### Slide template for budget / financial tables

@natalieworth something that would be useful for you to start on: we need a slide template that will work well for financial and budget information. Essentially tables with numbers. On a background that makes them legible. Probably much more neutral than the highly colorful slide backgrounds we employ in the rest of the deck. And avoiding colors that have financial implications (like red and green, etc.) Possible to get started on that?

**Comment by natalieworth** [comment]
​Sounds good! I can get a start on this @OpenMatt

**Comment by OpenMatt** [comment]
@natalieworth the draft deck is here: http://mzl.la/december_board_slides
please choose a new color for the budget / financials section and add a sample three column table there.
