### ISSUE TITLE
Advocacy: finalize KPI framework

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/strategy#55]
@adamlofting and @shaghdoosti were going to meet on this.

@adamlofting can you give a status update here? possible to have this closed by Nov 27?

**Comment by adamlofting** [comment]
I'm incorporating the latest feedback and comments today. 

Hoping for sign-off on the advocacy planning call tomorrow.

**Comment by OpenMatt** [comment]
thanks @adamlofting !

**Comment by OpenMatt** [comment]
@adamlofting sign off achieved! Can you ship this into the biz plan, and we'll consider it done for now? http://mzl.la/biz_plan

**Comment by adamlofting** [comment]
:boom:
