### ISSUE TITLE
Leadership: finalize KPI framework

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/strategy#56]
Take the feedback we got on iteration 1 and ship iteration 2

**Comment by OpenMatt** [comment]
@adamlofting let us know when you have a status update here?

**Comment by adamlofting** [comment]
I'm working on iteration 2 this morning with the hope for sign-off on the MLN call later today.

**Comment by OpenMatt** [comment]
thanks @adamlofting

**Comment by OpenMatt** [comment]
@adamlofting I believe you got sign-off -- so can you ship what you have into the business plan doc Thurs or Fri? http://mzl.la/biz_plan

**Comment by adamlofting** [comment]
I've updated the summary in the business plan, updated the longer form proposal document, and added related deliverables into the relevant parts of the MLN plan.

I'm going to treat the MLN KPI as finalized! :smile:
