### ISSUE TITLE
Advocacy: H1 2016 deliverables

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/strategy#58]
@shaghdoosti let's meet to discuss next steps here
- we have a good detailed list of H1 deliverables. And a good start on a more high-level roadmap. We should make sure we're clear on next steps here.

**Comment by OpenMatt** [comment]
### Next steps
- @shaghdoosti will take one more look at it this afternoon to make sure we capture the thoughts/notes from today
- then: Matt will clean up and ship version 1.0 Friday

**Comment by shaghdoosti** [comment]
I've taken another look. Andrea and Adam are going to be working on setting benchmarks that reflect the new KPI - there are few clarifications that Paul needs to make around language - but otherwise it's in a good place.

**Comment by HPaulJohnson** [comment]
I think I fixed outstanding language issues but let me know if more detail or clarification is necessary to get this shipped.

**Comment by OpenMatt** [comment]
Thanks guys. I'll take a final pass to clean up language tmrw (Fri) and then I think we can close this. Nice! :)
