### ISSUE TITLE
Nov 30 SCVP presentation

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/strategy#62]
### What we need:
- Apply this slide template: http://mzl.la/slide_template
- To this Google Slides presentation: http://mzl.la/nov30

We want to continue working in Google Slides for this, for easier collaborative editing, etc. 

@natalieworth: does that give you enough to go on to get started?

**Comment by OpenMatt** [comment]
Question for @msurman and Matt to work out: 
* should we use this template? 
* and should Matt start populating it with content?

**Comment by OpenMatt** [comment]
In addition to the design work, there's some content Matt will need to provide as well:
(@natalieworth: you can basically ignore this -- it's just for my own reference) 
- [ ] critical dependencies
- [ ] KPI frameworks
- [ ] H1 initiatives

MoCo's slide templates, in case they're helpful for Matt:
https://docs.google.com/presentation/d/19T7hHdEobaHUO7yW-PyHUkT--ZVSy5njep3GbJDw0rU/edit#slide=id.p

**Comment by OpenMatt** [comment]
@natalieworth are you working on this today?

**Comment by flukeout** [comment]
I'll be working on it @OpenMatt - gonna get started now.

**Comment by OpenMatt** [comment]
awesome thanks @flukeout

**Comment by flukeout** [comment]
Okay @OpenMatt, I've formatted the slides that looked finished - let me know when there is additional stuff to help with in there. Once we're done we can nuke the slides at the bottom that have all of the styles and colors, but please keep them there until we're finished.

**Comment by OpenMatt** [comment]
thanks @flukeout ! @msurman is working on slide content now, and may or may not have further design tweaks / requests for you today. I'll file them here if so.

**Comment by flukeout** [comment]
Okay @OpenMatt let me know as soon as you can!

**Comment by msurman** [comment]
@flukeout @OpenMatt huge thanks for all the work on this, the slides are looking good. No need for more design help.

**Comment by natalieworth** [comment]
Thanks @flukeout for jumping in on this! EOY things creeped up.
