### ISSUE TITLE
Create elevator pitch

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/strategy#68]
Overall plan: https://docs.google.com/document/d/1fyNVt6gW-qt2VU6eovOBR0fkCisS2PmG-8g3VDIPROo/edit

What is the ~30 sec elevator pitch for the change we are seeking to create?
What are the 2-3 top messages all MoFo staff and key MLN member should know/say about why we’re focusing on these priorities and what practical steps/milestones are next?
- e.g., Darren Walker & Ford Foundation's 'ending inequality'
- e.g., from the Open Web Fellows comms plan: “Mozilla is more than Firefox: we’re also empowering the next generation of open Internet leaders and advocates”
#### Roles
- Project manager: @samanthaburton 
- Consulted: @KevZawacki @HPaulJohnson 
- Decider: @msurman 
#### Examples
- This Ford Foundation asset does a good job. Maybe we could take some of the copy and thinking from the business plan opening summary to create something like this: https://www.fordfoundation.org/work/challenging-inequality/our-approach/

**Comment by KevZawacki** [comment]
@OpenMatt @samanthaburton  

Just to clarify: we are creating an elevator pitch for [this version](https://docs.google.com/document/d/1OipsGu8eWuTaT8J3T2-0CR3zB79SysATBLiTTBDGS5I/edit) of the business plan, correct?

I can put together a first draft before the 2/18 meeting with @HPaulJohnson @samanthaburton and Angela. To prevent possible overlap: is there any existing draft of this elevator pitch?

**Comment by samanthaburton** [comment]
@KevZawacki great question. The elevator pitch will actually be for [this version (0.9)](https://github.com/MozillaFoundation/strategy/issues/73#issuecomment-184011827) - with the caveat that I'm going to be working on developing a 1.0 version. However, the content shouldn't change so significantly as to require a full overhaul of an elevator pitch written for 0.9!

I don't believe that there is an existing draft, but would ask @OpenMatt and/or @msurman and/or @aplohman to verify.

**Comment by KevZawacki** [comment]
For reference: [v0.9](https://docs.google.com/document/d/1FvZErTiJivpNIXudhldWaU3-n5EbcaH5B9VLGeCNo1A/edit#heading=h.fx02yr6y4mov)

**Comment by OpenMatt** [comment]
@KevZawacki The copy in the intro that @samanthaburton mentioned should provide a good first draft or grist to pull from. Would be good to have you test and see with your keen copywriting eye whether you think that copy provides a solid summary of who we are and what we do going forward.

**Comment by KevZawacki** [comment]
Closing this ticket -- work being carried forward elsewhere and by Lotta.
