### ISSUE TITLE
Create a branding brief for Mozilla Leadership Network 

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/strategy#69]
- Is the “Mozilla (Learning) Leadership Network” an internal term or an external brand? (e.g., do we want a 'member' to think of themselves as a member of Mozilla, a member of the Mozilla Foundation, a member of MLN, a member of a specific program (e.g., Hive, a Fellowship, Mozilla Club?)
- If an external brand, do we ever 'launch' the MLN? Or is it a series of soft launches?
- How does Hive fit into Mozilla/MLN more broadly, especially in the context of the 2020 strategy? Are we keeping the brand? 
### Roles
- Project manager: ?
- Consulted: @HPaulJohnson @cassiemc @msurman @davidascher @ldecoursy
- Decider: @chrislarry33

**Comment by OpenMatt** [comment]
@davidascher says:
"The long game in my mind is people feel like they belong to Mozilla, and that belonging is qualified by either focus area/ profession /role or seniority level.  I am a “Mozilla club captain, check out my page at mozilla.club/rio”, “I am a scientist working with Mozilla, join me on mozillasciencelab”, “I am on the executive advisory team for Mozilla, let me recommend you for invitation”."

**Comment by OpenMatt** [comment]
Talked w. @samanthaburton -- we decided that this is a larger piece of ongoing work that doesn't primarily fit with our comms strategy for the plan, so closing this for now.

**Comment by samanthaburton** [comment]
@chrislarry33 @ldecoursy though we decided to close this, as its likely bigger than what we can do as part of the project to communicate MoFo's 2020 strategy, I'm wondering if it will be answered via the already planned H1 activities for MLN? If not, this is a flag that it these questions should be added to someone's docket, as I have a hunch it will eventually become a blocker.
