### ISSUE TITLE
Describe and map our new org structure

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/strategy#71]
What organizational structure are we evolving towards?
TLDR: two sub-units inside of a legal org with a shared ops support function
#### Roles

Project manager: @samanthaburton 
Consulted: @msurman @davidascher @chrislarry33 
Decider: @aplohman

**Comment by OpenMatt** [comment]
Sam: can you say more about where you see gaps in what already exists?

**Comment by OpenMatt** [comment]
@samanthaburton I'm going to suggest that you should work directly w. @aplohman on. As part of our larger internal communications and change management strategy.

**Comment by OpenMatt** [comment]
There are also assets / diagrams that already exist that can be pulled from slides, etc.

**Comment by samanthaburton** [comment]
From comment on the doc: "TLDR: two subunits inside of a legal org with a shared ops support function"
