### ISSUE TITLE
Document our milestones and activities

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/strategy#72]
What are the concrete milestones/activities for each of advocacy and MLN in 2016? (and beyond, if we can get there)
- For MLN, see Lainie’s document: [insert link]
- For Advocacy, see: [insert link]
#### Roles

Project manager: @OpenMatt (included in what you're doing for build.mozillafoundation.org)
Consulted: @davidascher @ldecoursy @openmatt + _______ ?
Decider: Mark

Overall plan: https://docs.google.com/document/d/1fyNVt6gW-qt2VU6eovOBR0fkCisS2PmG-8g3VDIPROo/edit

**Comment by OpenMatt** [comment]
What we already have / are working on:
- H1 Goals for Advocacy: https://github.com/MozillaFoundation/goals/issues?q=is%3Aissue+is%3Aopen+label%3AAdvocacy
- and Leadership: https://github.com/MozillaFoundation/goals/issues?q=is%3Aissue+is%3Aopen+label%3ALeadership
- Roadmap: https://docs.google.com/spreadsheets/d/1fr76MH_PJUJXAKvshj8kqTGInA2Sy6l4NoE9Bnxnmvc/edit#gid=517975171

**Comment by OpenMatt** [comment]
Sam: also interested to hear from you what more you think is needed beyond the H1 detail in the business plan

**Comment by samanthaburton** [comment]
@OpenMatt will the milestones linked above be included in the cal you're building for build.mozillafoundation.org? If so, I think that will cover this requirement.

**Comment by OpenMatt** [comment]
@samanthaburton yes, that is the goal. Should we close?

**Comment by samanthaburton** [comment]
Yep! Thanks.
