### ISSUE TITLE
Document how Advocacy and Leadership connect

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/strategy#73]
Overall plan: https://docs.google.com/document/d/1fyNVt6gW-qt2VU6eovOBR0fkCisS2PmG-8g3VDIPROo/edit

How do advocacy and MLN connect?
#### Roles

Project manager: @samanthaburton 
Consulted: @chrislarry33 @msurman @davidascher 
Decider: @msurman 

Deliverable: 
- a paragraph / bullets making this explicit, added to 1.0 business plan

**Comment by OpenMatt** [comment]
@davidascher says: My put is twofold:
- From a participant’s POV, the advocacy hub is the same thing as the alliance/networking pillar in the Advocacy plan
- We must have a pan-Mozilla unified approach to local organizing, which encompasses web literacy activities, advocacy activities, etc.

**Comment by OpenMatt** [comment]
Grist for this basic story:
1) they connect by focusing on the same three priorities: literacy, inclusion, privacy. they are two different tactics focused on the same goals. 
2) there's also new language on this in the Feb board slides. Have a look at those and see if that helps. 
3) we're also seeing obvious connection around our advocacy work creating teachable moments and educational assets. e.g., we run an encryption campaign, then re-purpose much of the material as teaching kits to teach others about privacy, etc.

**Comment by samanthaburton** [comment]
Took a first cut here: https://docs.google.com/document/d/1kwy5m5tl-m_SFrklQ1K1cL_0a0QPqjojhM8goGJL_7A/edit#

Ready for comment @msurman @davidascher @chrislarry33

**Comment by davidascher** [comment]
Added a comment on the doc. I think the poetry is right, but I think the
implementers are still unsure how we make the two groups coordinate given
this specific area of overlap.  Maybe not a problem for the business plan
comms though.

**Comment by msurman** [comment]
Looking at the first cut: we need to make the differences between the leadership and advocacy programs as clear as the similarities. There are more differences and non-connections than similarities and connections. 

E.g. leadership is high touch, small scale influence network vs. advocacy is large scale mass mobilizations. Some topics and techniques will work well in leadership (e.g. teaching deep skills, working out solutions, personal development) and some will work well in advocacy (e.g. large scale but shallow 'know how', showing force via a large constituency, etc.). 

The one place where there is more connectedness will be the 'advocacy hub' in the leadership network. That is where we'll use the leadership network model to recruit and train people who work alongside us on advocacy topics. This is the outgrowth of the open web fellows work with Ford.

**Comment by samanthaburton** [comment]
Drafts complete, will be incorporated into 1.0 version of the 2020 strategy. Closing as a separate issue.
