### ISSUE TITLE
Define how MoFo strategy connects with the whole of Mozilla 

### ISSUE THREAD

**Issue by OpenMatt** [MozillaFoundation/strategy#74]
Overall plan: https://docs.google.com/document/d/1fyNVt6gW-qt2VU6eovOBR0fkCisS2PmG-8g3VDIPROo/edit

Including: How does the strategy interact with Mozilla Innovation?
#### Roles:

Project manager: @samanthaburton 
Consulted: @msurman + Exec Team
Decider: @msurman

**Comment by OpenMatt** [comment]
@sam: what do you think about how this is answered right now in the opening summary of the business plan? (pages 5 - 7)
https://docs.google.com/document/d/1FvZErTiJivpNIXudhldWaU3-n5EbcaH5B9VLGeCNo1A/edit#heading=h.fx02yr6y4mov

**Comment by OpenMatt** [comment]
re: Innovation. See the new language on page 32
https://docs.google.com/document/d/1FvZErTiJivpNIXudhldWaU3-n5EbcaH5B9VLGeCNo1A/edit#heading=h.83dxjbvf0llz

re: connection to Firefox: there probably isn't any. But the product piece is mentioned in pages 5 - 7 of opening summary.

**Comment by sam** [comment]
Wrong @sam. :-)

**Comment by OpenMatt** [comment]
sorry @sam! :)

**Comment by samanthaburton** [comment]
The summary of the business plan is great - let's use that.
