### ISSUE TITLE
Create (internal) glossary of terms/style guide

### ISSUE THREAD

**Issue by samanthaburton** [MozillaFoundation/strategy#77]
Overall plan: https://docs.google.com/document/d/1fyNVt6gW-qt2VU6eovOBR0fkCisS2PmG-8g3VDIPROo/edit

**Roles**
Project manager (responsible): Kevin (or Paul)
Accountable: Sam
Consulted: Ben, Chris, Amira, Lainie, Matt, program managers, Cassie, Simon... etc
Decider: Mark

**Goals**
We have consistent language to be used across Mozilla (in internal and external comms) in a location and format that is easy to We have consistent language to be used across Mozilla (in internal and external comms) in a location and format that is easy to find and use.

Building on early-stage definitions/messaging briefs (https://docs.google.com/document/d/1N4w5i3iPzzfzLgQitoBLDhjqfqdpLRhYlIXGAGh9jTk/edit)

**Primary Audience(s)**
*MoCo Leadership
*MoCo Staff - close collaborators
*MoFo Staff
*Core MLN

**Some terms we want to include**
*Privacy (@benrito - dependency: #75)
*Inclusion (@benrito - dependency: #75)
*Web literacy (@benrito - dependency: #75)
*Tiers/key audiences (@chrislarry33 @ldecoursy - dependency: #76)
*Innovation (led by @davidascher)
*Leadership (@chrislarry33 @ldecoursy - dependency: #76)
*Membership (@chrislarry33 - included in MLN 2016 workplan)
*Mozilla Clubs (@chrislarry33 @amirad working on this - included in MLN 2016 workplan)
*Maker Party
*Mozilla Fellowships
*Convening
*Open badges
*Gigabit

**Comment by KevZawacki** [comment]
These are the latest paragraph briefs: https://docs.google.com/document/d/1Hf4Iaa4KdEx-rtqDUfAbO0POsM5K7Z3oNnoTjze576g/edit#heading=h.1hklriakz1v8

**Comment by KevZawacki** [comment]
Closing this ticket -- work being carried forward elsewhere and by Lotta.
