### ISSUE TITLE
1 pg summary of MoFo + 2020 strategy

### ISSUE THREAD

**Issue by samanthaburton** [MozillaFoundation/strategy#80]
Overall plan: https://docs.google.com/document/d/1fyNVt6gW-qt2VU6eovOBR0fkCisS2PmG-8g3VDIPROo/edit

**Roles**
Project manager (responsible): Kevin, Paul
Accountable: Sam
Consulted: ??
Decider: Mark

**Goals**
Provide a publicly shareable 1pg summary of MoFo and our 2020 strategy, drawing on our market differentiators/elevator pitch.Should provide building blocks MoFos can use to create tailored partner briefs and future external communications.

**Primary Audience(s)**
*MoCo Leadership
*MoCo Staff
*Everyone who’s been involved with MoFo over the last 5 yrs
*Core MLN
*Existing funders
*Targeted prospective funders

**Dependencies**
- Complete Business Plan v1.0 Ticket: https://github.com/MozillaFoundation/strategy/issues/79
- Create online home for 2020 strategy Ticket: https://github.com/MozillaFoundation/strategy/issues/78
- What is Mozilla's differentiation/strategic advantage? Ticket: https://github.com/MozillaFoundation/strategy/issues/67
- What is the ~30 sec elevator pitch for the change we are seeking to create? Ticket: https://github.com/MozillaFoundation/strategy/issues/68

**Comment by KevZawacki** [comment]
@samanthaburton @HPaulJohnson 

[First draft of our one-pager](https://docs.google.com/document/d/1vSnwN1giStIUODt1FH5XhhuQK9fot88kgjqu1q0Oi-Y/edit). 

Curious as to how we adapt the final product into our elevator pitch (#68). What do we add and subtract?

**Comment by KevZawacki** [comment]
Revisiting this ticket...

@samanthaburton I believe the copy we penned for mozilla.org/foundation does the trick nicely. 

[LINK](https://docs.google.com/document/d/1Gu7OrQRS_q_YV4cWhat2VKGq1zRvVTaBjFzeqLsRo6k/edit)

Closing out this ticket — let's reopen if we feel there's additional work to be done.
